export const images={
    noImage:require("../assets/images/noImage.png"),
    noInternet:require("../assets/images/noInternet.png"),
    kurti:require("../assets/images/kurti.png"),
    frock:require("../assets/images/frock.png"),
    kidFrock:require("../assets/images/kidFrock.png"),
    pant:require("../assets/images/pant.png"),
    payment1:require("../assets/images/payment1.png"),
    payment2:require("../assets/images/payment2.png"),
    cancel:require("../assets/images/cancel.png"),
    banner1:require("../assets/images/banner1.jpg"),
    foodBanner:require("../assets/images/foodBanner.jpg"),
    shoeBanner:require("../assets/images/shoeBanner.png"),
    wemanClothingBanner:require("../assets/images/wemanClothingBanner.png"),
    company1:require("../assets/images/company1.png"),
    company2:require("../assets/images/company2.jpg"),
    company3:require("../assets/images/company3.jpg"),
    mousam:require("../assets/images/mousam.png")
}